### ISSUE TITLE
Help！ error

### ISSUE THREAD

**Issue by xianyo** [FredChamp/AndroiNDK_GUI#2]
```
  #define HELPER_CLASS_NAME "com/ndkgui/helper/NDKHelper"
 #define HELPER_CLASS_SONAME "ndkgui"

 void android_main(struct android_app* state) {

    app_dummy();

    ndkGui::JNIHelper::Init(state->activity, HELPER_CLASS_NAME,HELPER_CLASS_SONAME);
}
```

error in ndkGui::JNIHelper::Init

in this:

```
   jmethodID constructor =
               env->GetMethodID(helper.jni_helper_java_class_, "<init>",
                                  "(Landroid/app/NativeActivity;)V");
```

Fatal signal 11 (SIGSEGV) at 0x0000005c (code=1), thread 17497

**Comment by FredChamp** [comment]
Hi xianyo,

Do you have more logs about the error ?

I think it's because you set `#define HELPER_CLASS_SONAME "ndkgui"` and the ndkgui is not a library.
This project compile two library: libJNIHelper.so and libJUIHelper.so.

You have to load them in an  implementation of android.app.NativeActivity  as following:

```
package com.your.packageName;

public class NativeActivity extends android.app.NativeActivity 
{
    private static final String TAG = "LauncherActivity";
    static 
    {
       System.loadLibrary("gnustl_shared");
       System.loadLibrary("JUIHelper");
       System.loadLibrary("JNIHelper");
    }
 }
```

Moreover `ndkGui::JNIHelper::Init(state->activity, HELPER_CLASS_NAME,HELPER_CLASS_SONAME);`is use to load a library at runtime in c++, them if you use the previous example you don't need to use it.

Best,
Fred

**Comment by xianyo** [comment]
Thanks!

I used cmake,but it has something wrong!

So i used Android-NDK.

please see my fork.
https://github.com/xianyo/ndkGui

It has errors.
Please help!
